version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    command: >
      /bin/bash -c "
        pwd
        /bin/bash
        && go run main.go"
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: character_search_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: character_search
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: